# -*- coding: utf-8 -*-
"""Laboratorio 18/5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1952v0pmWmdpTnWA1kvvedbn1WKa5RxSu
"""

#Laboratorio guiado
import folium

from folium.plugins import minimap
Heredia = folium.Map(location=(56.65883, -155.16678))
Heredia

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Heredia</b>'
my_map = folium.Map(location=[9.970705621104385, -84.12913688984136], zoom_start=16, tiles='stamenterrain')
folium.Marker(location=[9.970705621104385, -84.12913688984136], popup=popuptext, icon=folium.Icon(color="orange", icon="ok-sign")).add_to(my_map)

folium.Circle(location=[9.970705621104385, -84.12913688984136], color="purple", weight=6, fill_color="red", fill_opacity=0.5, tooltop="Heredia").add_to(my_map)

minimap= MiniMap(tile_layer='stamenterrain', position = 'bottomright')

my_map.add_child(minimap)

my_map.save('C:folium.html')

my_map

fig=Figure(width=1000, height=500)
fig.add_child(my_map)
fig